version: "3"

services:
  db:
    restart: unless-stopped
    image: postgres:14.0
    volumes:
      - merchant_mko_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mko_merchant
      - POSTGRES_USER=mko_merchant
      - POSTGRES_PASSWORD=mko_merchant
  app:
    restart: unless-stopped
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_NAME=mko_merchant
      - POSTGRES_USER=mko_merchant
      - POSTGRES_PASSWORD=mko_merchant
    depends_on:
      - db
volumes:
  merchant_mko_db:
    driver: local