# Generated by Django 4.1.3 on 2022-12-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
